# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jx2ITw_S-fgkzzJDob4U8WgvudTw_C7U
"""

import streamlit as st, numpy as np, joblib
from streamlit_drawable_canvas import st_canvas
from PIL import Image, ImageOps

st.title("📝 MNIST Digit Classifier")

@st.cache_resource
def load_model():
    return joblib.load("mnist_model.pkl")

model = load_model()

st.write("캔버스에 0-9 숫자를 그린 뒤 **Predict**를 눌러 보세요!")

canvas = st_canvas(
    fill_color="white",
    stroke_width=10,
    stroke_color="black",
    background_color="white",
    height=280,
    width=280,
    drawing_mode="freedraw",
    key="canvas",
)

if st.button("Predict"):
    if canvas.image_data is not None:
        # 캔버스(alpha) → 28×28 그레이스케일(0~255)
        img = Image.fromarray((255 - canvas.image_data[:, :, 3]).astype("uint8"))
        img = img.resize((28, 28)).convert("L")
        img = ImageOps.invert(img)                 # 흰 배경·검은 글씨로 변환
        x = np.array(img).reshape(1, -1).astype(float)
        pred = model.predict(x)[0]
        st.success(f"🧮 예측 결과: **{pred}**")
    else:
        st.error("먼저 숫자를 그려 주세요.")